version: '3'
    
services:
    web:
        build: .
        command: python ./solution/manage.py runserver 0.0.0.0:8000
        volumes:
        - .:/atlan_challenge
        ports:
        - "8000:8000"